include /etc/nginx/upstreams/*.conf;

server {
    listen 80;
    server_tokens off;
    return 301 https://$host$request_uri;

}

server {
    listen 443 ssl;
    server_name --hostname--;
    server_tokens off;

    error_page 497 =301 https://$host$request_uri;

	add_header X-Frame-Options "SAMEORIGIN";
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Content-Type-Options "nosniff";
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    charset                     utf-8;
    sendfile                    on;
    tcp_nopush                  on;
    tcp_nodelay                 off;
    reset_timedout_connection   on;

    include /etc/nginx/ssl.conf;
    include /etc/nginx/locations/*.conf;
}
