
location @seohburl {
    rewrite ^/(.+)$ /index.php?/$1 last;
}

location ^~ / {
    alias    /home/--id--/public_html/;
    index   index.php;
    try_files $uri $uri/ @seohburl;

    location ^~ /vendor/ {
            deny all;
            return 403;
    }


	location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)\$ {
		expires 7d;
		access_log off;
	    add_header Cache-Control "public";
	}

	location ~* \.(?:css|js)\$ {
	        expires 7d;
	        access_log off;
	        add_header Cache-Control "public";
	}

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.tpl$ {
        deny all;
    }

	location ~ /\.ht {
		deny  all;
	}


    location ~ \.php$ {
        location                    ~ \..*/.*\.php$ {return 403;}
        include        				/etc/nginx/fastcgi_params;

        #When https is enabled, make sure to uncomment line below
        fastcgi_param		    HTTPS 'on';

        fastcgi_pass   127.0.0.1:--port--;
        fastcgi_index  				index.php;
        fastcgi_param               SCRIPT_FILENAME $request_filename;
        fastcgi_hide_header         "X-Powered-By";
        fastcgi_buffers 16 64k;
        fastcgi_buffer_size 256k;

    }
}
